### ISSUE TITLE
When concurrency is forbidding and dkron exiting before it's done - job will never run again

### ISSUE THREAD

**Issue by zacharya19** [victorcoder/dkron#349]
Quick reproduce:
1. `docker-compose up -d`.
2. create job with this json:
```
{
    "name": "test_job_1",
    "command": "sleep 50",
    "schedule": "@every 10s",
    "concurrency": "forbid"
}
```
3. `docker-compose restart dkron`.

Now you can see dkron thinks the job is running, but it's not and forever we will see `scheduler: Skipping execution`.

EDIT: it's happening also when restarting dkron service (not only SIGKILL).

**Comment by koolay** [comment]
I have the same problem.

> This code has a concurrency scene bug,  should  be with a distributed  lock.

```
func (j *Job) isRunnable() bool {
	status := j.Status()

	if status == Running {
		if j.Concurrency == ConcurrencyAllow {
			return true
		} else if j.Concurrency == ConcurrencyForbid {
			log.WithFields(logrus.Fields{
				"job":         j.Name,
				"concurrency": j.Concurrency,
				"job_status":  status,
			}).Debug("scheduler: Skipping execution")
			return false
		}
	}

	return true
}

```

**Comment by zacharya19** [comment]
I believe each execution should save the process id so dkron would be able to check the status.

**Comment by victorcoder** [comment]
Fixed in #359

**Comment by zacharya19** [comment]
@victorcoder I think the issue still exists.
I added GetStatus to the log and I see this:
 `concurrency=forbid get_status_function=failed job=test_job_1 job_status=running node=39d4b2198b72`

I think it's because the check for:
`if j.Status == StatusNotSet {`

**Comment by victorcoder** [comment]
Should be fixed in #383
