### ISSUE TITLE
Specifying executing node count does not work

### ISSUE THREAD

**Issue by whizz** [victorcoder/dkron#55]
I am creating a simple example job, that I want to run only on one server in the cluster every five seconds:

Job definition:
```json
{
	"name": "uptimesingle",
	"schedule": "*/5 * * * * *",
	"command": "uptime",
	"tags": {
		"role": "nrh_dkron_server:1"
	}
}
```

Three servers have the corresponding role tag. The first execution happens on only one server, but all subsequent executions happen on all the servers:

```json
[{
	"job_name": "uptimesingle",
	"started_at": "2015-12-17T10:47:35.003082159+01:00",
	"finished_at": "2015-12-17T10:47:35.021981973+01:00",
	"success": true,
	"output": "IDEwOjQ3OjM1IHVwIDQ2OCBkYXlzLCA0MiBtaW4sICA1IHVzZXJzLCAgbG9hZCBhdmVyYWdlOiAwLjg3LCAwLjc4LCAwLjczCg==",
	"node_name": "cz-dc-v-213.mall.local",
	"group": 1450345655000284700,
	"job": {
		"name": "uptimesingle",
		"schedule": "*/5 * * * * *",
		"command": "uptime",
		"owner": "",
		"owner_email": "",
		"run_as_user": "",
		"success_count": 0,
		"error_count": 0,
		"last_success": "0001-01-01T00:00:00Z",
		"last_error": "0001-01-01T00:00:00Z",
		"disabled": false,
		"tags": {
			"role": "nrh_dkron_server"
		}
	}
}, {
	"job_name": "uptimesingle",
	"started_at": "2015-12-17T10:47:40.001009965+01:00",
	"finished_at": "2015-12-17T10:47:40.005702977+01:00",
	"success": true,
	"output": "IDEwOjQ3OjQwIHVwIDQ2OCBkYXlzLCA0MiBtaW4sICA1IHVzZXJzLCAgbG9hZCBhdmVyYWdlOiAwLjg4LCAwLjc4LCAwLjczCg==",
	"node_name": "cz-dc-v-213.mall.local",
	"group": 1450345660000339700,
	"job": {
		"name": "uptimesingle",
		"schedule": "*/5 * * * * *",
		"command": "uptime",
		"owner": "",
		"owner_email": "",
		"run_as_user": "",
		"success_count": 0,
		"error_count": 0,
		"last_success": "0001-01-01T00:00:00Z",
		"last_error": "0001-01-01T00:00:00Z",
		"disabled": false,
		"tags": {
			"role": "nrh_dkron_server"
		}
	}
}, {
	"job_name": "uptimesingle",
	"started_at": "2015-12-17T10:47:40.064416976+01:00",
	"finished_at": "2015-12-17T10:47:40.067118607+01:00",
	"success": true,
	"output": "IDEwOjQ3OjQwIHVwIDEzMyBkYXlzLCAyMToyNiwgIDAgdXNlcnMsICBsb2FkIGF2ZXJhZ2U6IDAuMDAsIDAuMDAsIDAuMDAK",
	"node_name": "cz-dc-v-214.mall.local",
	"group": 1450345660000339700,
	"job": {
		"name": "uptimesingle",
		"schedule": "*/5 * * * * *",
		"command": "uptime",
		"owner": "",
		"owner_email": "",
		"run_as_user": "",
		"success_count": 0,
		"error_count": 0,
		"last_success": "0001-01-01T00:00:00Z",
		"last_error": "0001-01-01T00:00:00Z",
		"disabled": false,
		"tags": {
			"role": "nrh_dkron_server"
		}
	}
}, {
	"job_name": "uptimesingle",
	"started_at": "2015-12-17T10:47:40.06495417+01:00",
	"finished_at": "2015-12-17T10:47:40.069631854+01:00",
	"success": true,
	"output": "IDEwOjQ3OjQwIHVwIDM3OCBkYXlzLCAxOTo1MSwgIDAgdXNlcnMsICBsb2FkIGF2ZXJhZ2U6IDAuMDMsIDAuMDMsIDAuMDAK",
	"node_name": "cz-dc-v-211.mall.local",
	"group": 1450345660000339700,
	"job": {
		"name": "uptimesingle",
		"schedule": "*/5 * * * * *",
		"command": "uptime",
		"owner": "",
		"owner_email": "",
		"run_as_user": "",
		"success_count": 0,
		"error_count": 0,
		"last_success": "0001-01-01T00:00:00Z",
		"last_error": "0001-01-01T00:00:00Z",
		"disabled": false,
		"tags": {
			"role": "nrh_dkron_server"
		}
	}
}, {
	"job_name": "uptimesingle",
	"started_at": "2015-12-17T10:47:45.000775552+01:00",
	"finished_at": "2015-12-17T10:47:45.004132583+01:00",
	"success": true,
	"output": "IDEwOjQ3OjQ1IHVwIDQ2OCBkYXlzLCA0MiBtaW4sICA1IHVzZXJzLCAgbG9hZCBhdmVyYWdlOiAwLjg5LCAwLjc5LCAwLjczCg==",
	"node_name": "cz-dc-v-213.mall.local",
	"group": 1450345665000309200,
	"job": {
		"name": "uptimesingle",
		"schedule": "*/5 * * * * *",
		"command": "uptime",
		"owner": "",
		"owner_email": "",
		"run_as_user": "",
		"success_count": 0,
		"error_count": 0,
		"last_success": "0001-01-01T00:00:00Z",
		"last_error": "0001-01-01T00:00:00Z",
		"disabled": false,
		"tags": {
			"role": "nrh_dkron_server"
		}
	}
}, {
	"job_name": "uptimesingle",
	"started_at": "2015-12-17T10:47:45.064704859+01:00",
	"finished_at": "2015-12-17T10:47:45.067112311+01:00",
	"success": true,
	"output": "IDEwOjQ3OjQ1IHVwIDEzMyBkYXlzLCAyMToyNiwgIDAgdXNlcnMsICBsb2FkIGF2ZXJhZ2U6IDAuMDAsIDAuMDAsIDAuMDAK",
	"node_name": "cz-dc-v-214.mall.local",
	"group": 1450345665000309200,
	"job": {
		"name": "uptimesingle",
		"schedule": "*/5 * * * * *",
		"command": "uptime",
		"owner": "",
		"owner_email": "",
		"run_as_user": "",
		"success_count": 0,
		"error_count": 0,
		"last_success": "0001-01-01T00:00:00Z",
		"last_error": "0001-01-01T00:00:00Z",
		"disabled": false,
		"tags": {
			"role": "nrh_dkron_server"
		}
	}
}, {
	"job_name": "uptimesingle",
	"started_at": "2015-12-17T10:47:45.065110494+01:00",
	"finished_at": "2015-12-17T10:47:45.067889715+01:00",
	"success": true,
	"output": "IDEwOjQ3OjQ1IHVwIDM3OCBkYXlzLCAxOTo1MSwgIDAgdXNlcnMsICBsb2FkIGF2ZXJhZ2U6IDAuMDIsIDAuMDMsIDAuMDAK",
	"node_name": "cz-dc-v-211.mall.local",
	"group": 1450345665000309200,
	"job": {
		"name": "uptimesingle",
		"schedule": "*/5 * * * * *",
		"command": "uptime",
		"owner": "",
		"owner_email": "",
		"run_as_user": "",
		"success_count": 0,
		"error_count": 0,
		"last_success": "0001-01-01T00:00:00Z",
		"last_error": "0001-01-01T00:00:00Z",
		"disabled": false,
		"tags": {
			"role": "nrh_dkron_server"
		}
	}
}, {
	"job_name": "uptimesingle",
	"started_at": "2015-12-17T10:47:50.002168058+01:00",
	"finished_at": "2015-12-17T10:47:50.00769461+01:00",
	"success": true,
	"output": "IDEwOjQ3OjUwIHVwIDQ2OCBkYXlzLCA0MiBtaW4sICA1IHVzZXJzLCAgbG9hZCBhdmVyYWdlOiAwLjkwLCAwLjc5LCAwLjc0Cg==",
	"node_name": "cz-dc-v-213.mall.local",
	"group": 1450345670000230100,
	"job": {
		"name": "uptimesingle",
		"schedule": "*/5 * * * * *",
		"command": "uptime",
		"owner": "",
		"owner_email": "",
		"run_as_user": "",
		"success_count": 0,
		"error_count": 0,
		"last_success": "0001-01-01T00:00:00Z",
		"last_error": "0001-01-01T00:00:00Z",
		"disabled": false,
		"tags": {
			"role": "nrh_dkron_server"
		}
	}
}, {
	"job_name": "uptimesingle",
	"started_at": "2015-12-17T10:47:50.064456879+01:00",
	"finished_at": "2015-12-17T10:47:50.066860985+01:00",
	"success": true,
	"output": "IDEwOjQ3OjUwIHVwIDEzMyBkYXlzLCAyMToyNiwgIDAgdXNlcnMsICBsb2FkIGF2ZXJhZ2U6IDAuMDAsIDAuMDAsIDAuMDAK",
	"node_name": "cz-dc-v-214.mall.local",
	"group": 1450345670000230100,
	"job": {
		"name": "uptimesingle",
		"schedule": "*/5 * * * * *",
		"command": "uptime",
		"owner": "",
		"owner_email": "",
		"run_as_user": "",
		"success_count": 0,
		"error_count": 0,
		"last_success": "0001-01-01T00:00:00Z",
		"last_error": "0001-01-01T00:00:00Z",
		"disabled": false,
		"tags": {
			"role": "nrh_dkron_server"
		}
	}
}, {
	"job_name": "uptimesingle",
	"started_at": "2015-12-17T10:47:50.065033688+01:00",
	"finished_at": "2015-12-17T10:47:50.068118228+01:00",
	"success": true,
	"output": "IDEwOjQ3OjUwIHVwIDM3OCBkYXlzLCAxOTo1MSwgIDAgdXNlcnMsICBsb2FkIGF2ZXJhZ2U6IDAuMDIsIDAuMDMsIDAuMDAK",
	"node_name": "cz-dc-v-211.mall.local",
	"group": 1450345670000230100,
	"job": {
		"name": "uptimesingle",
		"schedule": "*/5 * * * * *",
		"command": "uptime",
		"owner": "",
		"owner_email": "",
		"run_as_user": "",
		"success_count": 0,
		"error_count": 0,
		"last_success": "0001-01-01T00:00:00Z",
		"last_error": "0001-01-01T00:00:00Z",
		"disabled": false,
		"tags": {
			"role": "nrh_dkron_server"
		}
	}
}]
```

**Comment by victorcoder** [comment]
@whizz Something weird is happening here, you executions doesn't seem to belong to the job definition, as you can see in the job definition embedded in each execution the tags are:
```
"tags": {
            "role": "nrh_dkron_server"
        }
```

And should be:
```
"tags": {
        "role": "nrh_dkron_server:1"
    }
```

What version are you using?

**Comment by whizz** [comment]
I am using latest 0.6.0

**Comment by victorcoder** [comment]
I spotted the bug and fixed in https://github.com/victorcoder/dkron/pull/60

Thanks for the testing

**Comment by whizz** [comment]
Unfortunately, it's still not working. I tried 0.6.1 and the behavior is the same. 

Job definition:
```json
{
    "name": "uptime20151221",
    "schedule": "*/10 * * * * *",
    "command": "uptime",
    "owner": "",
    "owner_email": "",
    "run_as_user": "",
    "success_count": 16,
    "error_count": 0,
    "last_success": "2015-12-21T10:05:00.083201311+01:00",
    "last_error": "0001-01-01T00:00:00Z",
    "disabled": false,
    "tags": {
        "role": "nrh_dkron_server:1"
    }
}
```

Executions:

```json
[

{

    "job_name": "uptime20151221",
    "started_at": "2015-12-21T10:03:50.084912411+01:00",
    "finished_at": "2015-12-21T10:03:50.099487464+01:00",
    "success": true,
    "output": "IDEwOjAzOjUwIHVwIDM4MiBkYXlzLCAxOTowNywgIDAgdXNlcnMsICBsb2FkIGF2ZXJhZ2U6IDAuMjQsIDAuMjEsIDAuMTEK",
    "node_name": "cz-dc-v-211.mall.local",
    "group": ​1450688630000273965,
    "job": 

{

    "name": "uptime20151221",
    "schedule": "*/10 * * * * *",
    "command": "uptime",
    "owner": "",
    "owner_email": "",
    "run_as_user": "",
    "success_count": ​0,
    "error_count": ​0,
    "last_success": "0001-01-01T00:00:00Z",
    "last_error": "0001-01-01T00:00:00Z",
    "disabled": false,
    "tags": 

        {
            "role": "nrh_dkron_server"
        }
    }

},
{

    "job_name": "uptime20151221",
    "started_at": "2015-12-21T10:04:00.000599135+01:00",
    "finished_at": "2015-12-21T10:04:00.003453523+01:00",
    "success": true,
    "output": "IDEwOjA0OjAwIHVwIDQ3MSBkYXlzLCAyMzo1OSwgIDUgdXNlcnMsICBsb2FkIGF2ZXJhZ2U6IDAuOTYsIDAuOTAsIDAuNzYK",
    "node_name": "cz-dc-v-213.mall.local",
    "group": ​1450688640000194942,
    "job": 

{

    "name": "uptime20151221",
    "schedule": "*/10 * * * * *",
    "command": "uptime",
    "owner": "",
    "owner_email": "",
    "run_as_user": "",
    "success_count": ​0,
    "error_count": ​0,
    "last_success": "0001-01-01T00:00:00Z",
    "last_error": "0001-01-01T00:00:00Z",
    "disabled": false,
    "tags": 

        {
            "role": "nrh_dkron_server"
        }
    }

},
{

    "job_name": "uptime20151221",
    "started_at": "2015-12-21T10:04:00.080118972+01:00",
    "finished_at": "2015-12-21T10:04:00.083194838+01:00",
    "success": true,
    "output": "IDEwOjA0OjAwIHVwIDEzNyBkYXlzLCAyMDo0MiwgIDAgdXNlcnMsICBsb2FkIGF2ZXJhZ2U6IDAuMDAsIDAuMDEsIDAuMDAK",
    "node_name": "cz-dc-v-214.mall.local",
    "group": ​1450688640000194942,
    "job": 

{

    "name": "uptime20151221",
    "schedule": "*/10 * * * * *",
    "command": "uptime",
    "owner": "",
    "owner_email": "",
    "run_as_user": "",
    "success_count": ​0,
    "error_count": ​0,
    "last_success": "0001-01-01T00:00:00Z",
    "last_error": "0001-01-01T00:00:00Z",
    "disabled": false,
    "tags": 

        {
            "role": "nrh_dkron_server"
        }
    }

},
{

    "job_name": "uptime20151221",
    "started_at": "2015-12-21T10:04:00.080418988+01:00",
    "finished_at": "2015-12-21T10:04:00.08390867+01:00",
    "success": true,
    "output": "IDEwOjA0OjAwIHVwIDM4MiBkYXlzLCAxOTowOCwgIDAgdXNlcnMsICBsb2FkIGF2ZXJhZ2U6IDAuMjAsIDAuMjAsIDAuMTEK",
    "node_name": "cz-dc-v-211.mall.local",
    "group": ​1450688640000194942,
    "job": 

{

    "name": "uptime20151221",
    "schedule": "*/10 * * * * *",
    "command": "uptime",
    "owner": "",
    "owner_email": "",
    "run_as_user": "",
    "success_count": ​0,
    "error_count": ​0,
    "last_success": "0001-01-01T00:00:00Z",
    "last_error": "0001-01-01T00:00:00Z",
    "disabled": false,
    "tags": 

        {
            "role": "nrh_dkron_server"
        }
    }

},
{

    "job_name": "uptime20151221",
    "started_at": "2015-12-21T10:04:10.000856912+01:00",
    "finished_at": "2015-12-21T10:04:10.004640213+01:00",
    "success": true,
    "output": "IDEwOjA0OjEwIHVwIDQ3MSBkYXlzLCAyMzo1OSwgIDUgdXNlcnMsICBsb2FkIGF2ZXJhZ2U6IDEuMDQsIDAuOTIsIDAuNzcK",
    "node_name": "cz-dc-v-213.mall.local",
    "group": ​1450688650000365412,
    "job": 

{

    "name": "uptime20151221",
    "schedule": "*/10 * * * * *",
    "command": "uptime",
    "owner": "",
    "owner_email": "",
    "run_as_user": "",
    "success_count": ​0,
    "error_count": ​0,
    "last_success": "0001-01-01T00:00:00Z",
    "last_error": "0001-01-01T00:00:00Z",
    "disabled": false,
    "tags": 

        {
            "role": "nrh_dkron_server"
        }
    }

},
{

    "job_name": "uptime20151221",
    "started_at": "2015-12-21T10:04:10.079925794+01:00",
    "finished_at": "2015-12-21T10:04:10.083452121+01:00",
    "success": true,
    "output": "IDEwOjA0OjEwIHVwIDEzNyBkYXlzLCAyMDo0MywgIDAgdXNlcnMsICBsb2FkIGF2ZXJhZ2U6IDAuMDAsIDAuMDEsIDAuMDAK",
    "node_name": "cz-dc-v-214.mall.local",
    "group": ​1450688650000365412,
    "job": 

{

    "name": "uptime20151221",
    "schedule": "*/10 * * * * *",
    "command": "uptime",
    "owner": "",
    "owner_email": "",
    "run_as_user": "",
    "success_count": ​0,
    "error_count": ​0,
    "last_success": "0001-01-01T00:00:00Z",
    "last_error": "0001-01-01T00:00:00Z",
    "disabled": false,
    "tags": 

        {
            "role": "nrh_dkron_server"
        }
    }

},
{

    "job_name": "uptime20151221",
    "started_at": "2015-12-21T10:04:10.080275783+01:00",
    "finished_at": "2015-12-21T10:04:10.083116711+01:00",
    "success": true,
    "output": "IDEwOjA0OjEwIHVwIDM4MiBkYXlzLCAxOTowOCwgIDAgdXNlcnMsICBsb2FkIGF2ZXJhZ2U6IDAuMTcsIDAuMTksIDAuMTEK",
    "node_name": "cz-dc-v-211.mall.local",
    "group": ​1450688650000365412,
    "job": 

{

    "name": "uptime20151221",
    "schedule": "*/10 * * * * *",
    "command": "uptime",
    "owner": "",
    "owner_email": "",
    "run_as_user": "",
    "success_count": ​0,
    "error_count": ​0,
    "last_success": "0001-01-01T00:00:00Z",
    "last_error": "0001-01-01T00:00:00Z",
    "disabled": false,
    "tags": 

        {
            "role": "nrh_dkron_server"
        }
    }

},
{

    "job_name": "uptime20151221",
    "started_at": "2015-12-21T10:04:20.000726205+01:00",
    "finished_at": "2015-12-21T10:04:20.003752703+01:00",
    "success": true,
    "output": "IDEwOjA0OjIwIHVwIDQ3MSBkYXlzLCAyMzo1OSwgIDUgdXNlcnMsICBsb2FkIGF2ZXJhZ2U6IDEuMDMsIDAuOTIsIDAuNzcK",
    "node_name": "cz-dc-v-213.mall.local",
    "group": ​1450688660000278399,
    "job": 

{

    "name": "uptime20151221",
    "schedule": "*/10 * * * * *",
    "command": "uptime",
    "owner": "",
    "owner_email": "",
    "run_as_user": "",
    "success_count": ​0,
    "error_count": ​0,
    "last_success": "0001-01-01T00:00:00Z",
    "last_error": "0001-01-01T00:00:00Z",
    "disabled": false,
    "tags": 

        {
            "role": "nrh_dkron_server"
        }
    }

},
{

    "job_name": "uptime20151221",
    "started_at": "2015-12-21T10:04:20.07970281+01:00",
    "finished_at": "2015-12-21T10:04:20.084218902+01:00",
    "success": true,
    "output": "IDEwOjA0OjIwIHVwIDEzNyBkYXlzLCAyMDo0MywgIDAgdXNlcnMsICBsb2FkIGF2ZXJhZ2U6IDAuMDAsIDAuMDEsIDAuMDAK",
    "node_name": "cz-dc-v-214.mall.local",
    "group": ​1450688660000278399,
    "job": 

{

    "name": "uptime20151221",
    "schedule": "*/10 * * * * *",
    "command": "uptime",
    "owner": "",
    "owner_email": "",
    "run_as_user": "",
    "success_count": ​0,
    "error_count": ​0,
    "last_success": "0001-01-01T00:00:00Z",
    "last_error": "0001-01-01T00:00:00Z",
    "disabled": false,
    "tags": 

        {
            "role": "nrh_dkron_server"
        }
    }

},
{

    "job_name": "uptime20151221",
    "started_at": "2015-12-21T10:04:20.080449838+01:00",
    "finished_at": "2015-12-21T10:04:20.083152242+01:00",
    "success": true,
    "output": "IDEwOjA0OjIwIHVwIDM4MiBkYXlzLCAxOTowOCwgIDAgdXNlcnMsICBsb2FkIGF2ZXJhZ2U6IDAuMTQsIDAuMTksIDAuMTEK",
    "node_name": "cz-dc-v-211.mall.local",
    "group": ​1450688660000278399,
    "job": 

{

    "name": "uptime20151221",
    "schedule": "*/10 * * * * *",
    "command": "uptime",
    "owner": "",
    "owner_email": "",
    "run_as_user": "",
    "success_count": ​0,
    "error_count": ​0,
    "last_success": "0001-01-01T00:00:00Z",
    "last_error": "0001-01-01T00:00:00Z",
    "disabled": false,
    "tags": 

        {
            "role": "nrh_dkron_server"
        }
    }

},
{

    "job_name": "uptime20151221",
    "started_at": "2015-12-21T10:04:30.001022246+01:00",
    "finished_at": "2015-12-21T10:04:30.006653609+01:00",
    "success": true,
    "output": "IDEwOjA0OjMwIHVwIDQ3MSBkYXlzLCAyMzo1OSwgIDUgdXNlcnMsICBsb2FkIGF2ZXJhZ2U6IDEuMDMsIDAuOTIsIDAuNzcK",
    "node_name": "cz-dc-v-213.mall.local",
    "group": ​1450688670000398125,
    "job": 

{

    "name": "uptime20151221",
    "schedule": "*/10 * * * * *",
    "command": "uptime",
    "owner": "",
    "owner_email": "",
    "run_as_user": "",
    "success_count": ​0,
    "error_count": ​0,
    "last_success": "0001-01-01T00:00:00Z",
    "last_error": "0001-01-01T00:00:00Z",
    "disabled": false,
    "tags": 

        {
            "role": "nrh_dkron_server"
        }
    }

},
{

    "job_name": "uptime20151221",
    "started_at": "2015-12-21T10:04:30.079775433+01:00",
    "finished_at": "2015-12-21T10:04:30.082153846+01:00",
    "success": true,
    "output": "IDEwOjA0OjMwIHVwIDEzNyBkYXlzLCAyMDo0MywgIDAgdXNlcnMsICBsb2FkIGF2ZXJhZ2U6IDAuMDAsIDAuMDEsIDAuMDAK",
    "node_name": "cz-dc-v-214.mall.local",
    "group": ​1450688670000398125,
    "job": 

{

    "name": "uptime20151221",
    "schedule": "*/10 * * * * *",
    "command": "uptime",
    "owner": "",
    "owner_email": "",
    "run_as_user": "",
    "success_count": ​0,
    "error_count": ​0,
    "last_success": "0001-01-01T00:00:00Z",
    "last_error": "0001-01-01T00:00:00Z",
    "disabled": false,
    "tags": 

        {
            "role": "nrh_dkron_server"
        }
    }

},
{

    "job_name": "uptime20151221",
    "started_at": "2015-12-21T10:04:30.080502914+01:00",
    "finished_at": "2015-12-21T10:04:30.08370006+01:00",
    "success": true,
    "output": "IDEwOjA0OjMwIHVwIDM4MiBkYXlzLCAxOTowOCwgIDAgdXNlcnMsICBsb2FkIGF2ZXJhZ2U6IDAuMTIsIDAuMTgsIDAuMTEK",
    "node_name": "cz-dc-v-211.mall.local",
    "group": ​1450688670000398125,
    "job": 

{

    "name": "uptime20151221",
    "schedule": "*/10 * * * * *",
    "command": "uptime",
    "owner": "",
    "owner_email": "",
    "run_as_user": "",
    "success_count": ​0,
    "error_count": ​0,
    "last_success": "0001-01-01T00:00:00Z",
    "last_error": "0001-01-01T00:00:00Z",
    "disabled": false,
    "tags": 

            {
                "role": "nrh_dkron_server"
            }
        }
    }

]
```
